/**
 * AI Forecast Assistant — frontend behaviour.
 *
 * The important assertions are the trust ones: the UI must surface an
 * unverified figure rather than hide it, must degrade cleanly when the
 * assistant is not configured, and must never contain an API key.
 */
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import type { ReactNode } from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

import { Assistant } from '../pages/Assistant'

const STATUS_OK = {
  available: true, enabled: true, provider: 'gemini', model: 'gemini-2.0-flash',
  reasons: [], key_configured: true, max_question_chars: 800,
  guarantees: ['The assistant reads only. It cannot modify forecasts.'],
  refusals: {
    modifying_forecasts: 'the model is frozen; no write path exists',
    price_what_if: 'the model uses price as context, not as a causal lever',
    prediction_intervals: 'the model emits point forecasts only',
  },
}

const STATUS_MISSING_KEY = {
  ...STATUS_OK,
  available: false, model: null, key_configured: false,
  reasons: ['GEMINI_API_KEY is not set in the environment'],
}

const SUGGESTIONS = {
  context: 'whole chain',
  suggestions: ['Which items need attention right now?', 'How accurate is this model?'],
}

const GROUNDED_ANSWER = {
  answer: 'Demand is expected to stay broadly stable over the next 28 days.',
  intent: 'series', model: 'gemini-2.0-flash', grounded: true,
  ungrounded_numbers: [], injection_suspected: false,
  context_keys: ['forecast', 'recent_history', 'series'],
  elapsed_ms: 812,
  disclaimer: 'Generated by an AI assistant from verified backend data. The model is frozen.',
}

const UNGROUNDED_ANSWER = {
  ...GROUNDED_ANSWER,
  answer: 'Demand will total exactly 87654.31 units.',
  grounded: false,
  ungrounded_numbers: [87654.31],
}

function mockApi(status: unknown, ask: unknown = GROUNDED_ANSWER, askOk = true) {
  vi.stubGlobal('fetch', vi.fn(async (url: string, init?: RequestInit) => {
    const ok = (body: unknown) => ({
      ok: true, status: 200, statusText: 'OK',
      json: async () => body, headers: { get: () => null },
    })
    if (String(url).includes('/genai/status')) return ok(status)
    if (String(url).includes('/genai/suggestions')) return ok(SUGGESTIONS)
    if (String(url).includes('/genai/ask') && init?.method === 'POST') {
      if (!askOk) {
        return {
          ok: false, status: 503, statusText: 'Service Unavailable',
          json: async () => ({
            error: 'service_unavailable',
            message: 'The AI assistant is not configured in this deployment.',
            context: { remedy: 'Set GEMINI_API_KEY in the API environment.' },
          }),
          headers: { get: () => null },
        }
      }
      return ok(ask)
    }
    return ok({})
  }))
}

function wrap(node: ReactNode, route = '/assistant') {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={qc}>
      <MemoryRouter initialEntries={[route]}>{node}</MemoryRouter>
    </QueryClientProvider>,
  )
}

describe('Assistant — availability', () => {
  beforeEach(() => vi.unstubAllGlobals())

  it('explains why it is unavailable instead of showing a broken input', async () => {
    mockApi(STATUS_MISSING_KEY)
    wrap(<Assistant />)
    await waitFor(() =>
      expect(screen.getByText(/not configured in this deployment/i)).toBeInTheDocument())
    expect(screen.getByText(/GEMINI_API_KEY is not set/i)).toBeInTheDocument()
    // and no way to type a question
    expect(screen.queryByRole('textbox')).not.toBeInTheDocument()
  })

  it('states that the rest of the application still works without it', async () => {
    mockApi(STATUS_MISSING_KEY)
    wrap(<Assistant />)
    await waitFor(() =>
      expect(screen.getByText(/works without it/i)).toBeInTheDocument())
  })

  it('shows the input and starter suggestions when configured', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    expect(screen.getByText('Which items need attention right now?')).toBeInTheDocument()
  })
})

describe('Assistant — asking', () => {
  beforeEach(() => vi.unstubAllGlobals())

  it('sends the question and renders the answer', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())

    await user.type(screen.getByRole('textbox'), 'Explain this forecast')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))

    await waitFor(() =>
      expect(screen.getByText(/broadly stable over the next 28 days/i)).toBeInTheDocument())
  })

  it('shows which data the answer was built from', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    await user.type(screen.getByRole('textbox'), 'Explain this forecast')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))

    await waitFor(() =>
      expect(screen.getByText(/all figures traced to backend data/i)).toBeInTheDocument())
    expect(screen.getByText(/812 ms/)).toBeInTheDocument()
  })

  it('WARNS when a figure could not be traced to backend data', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK, UNGROUNDED_ANSWER)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    await user.type(screen.getByRole('textbox'), 'Explain this forecast')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))

    await waitFor(() =>
      expect(screen.getByText(/could not be traced/i)).toBeInTheDocument())
    // the offending number is named so a user can check it — it appears both in
    // the answer itself and in the warning, which is the intended behaviour
    expect(screen.getAllByText(/87654\.31/).length).toBeGreaterThanOrEqual(1)
    expect(screen.getByText(/unverified/i)).toBeInTheDocument()
  })

  it('sends the selected series as context when focused', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK)
    wrap(<Assistant />, '/assistant?store=CA_3&item=FOODS_3_090')
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    await user.type(screen.getByRole('textbox'), 'Explain this')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))

    await waitFor(() => {
      const call = (globalThis.fetch as ReturnType<typeof vi.fn>).mock.calls
        .find((c) => String(c[0]).includes('/genai/ask'))
      expect(call).toBeTruthy()
      const body = JSON.parse((call![1] as RequestInit).body as string)
      expect(body.store_id).toBe('CA_3')
      expect(body.item_id).toBe('FOODS_3_090')
    })
  })

  it('shows a focus banner for the selected series', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />, '/assistant?store=CA_3&item=FOODS_3_090')
    await waitFor(() => expect(screen.getByText('FOODS_3_090')).toBeInTheDocument())
    expect(screen.getByText('CA_3')).toBeInTheDocument()
  })

  it('renders an error state when the request fails', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK, null, false)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    await user.type(screen.getByRole('textbox'), 'Explain this forecast')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))

    await waitFor(() => expect(screen.getByRole('alert')).toBeInTheDocument())
    expect(screen.getByText(/Set GEMINI_API_KEY/i)).toBeInTheDocument()
  })

  it('will not send an empty question', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    expect(screen.getByRole('button', { name: /^ask$/i })).toBeDisabled()
  })
})

describe('Assistant — trust framing', () => {
  beforeEach(() => vi.unstubAllGlobals())

  it('explains the retrieval pipeline so the user knows what was sent', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() =>
      expect(screen.getByText(/How this assistant works/i)).toBeInTheDocument())
    expect(screen.getByText(/never the dataset/i)).toBeInTheDocument()
    expect(screen.getByText(/never directly to an AI provider/i)).toBeInTheDocument()
  })

  it('lists what the assistant refuses to do', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() =>
      expect(screen.getByText(/What it will not do/i)).toBeInTheDocument())
    expect(screen.getByText(/no write path exists/i)).toBeInTheDocument()
    expect(screen.getByText(/point forecasts only/i)).toBeInTheDocument()
  })

  it('states that the model is frozen', async () => {
    mockApi(STATUS_OK)
    wrap(<Assistant />)
    await waitFor(() =>
      expect(screen.getAllByText(/frozen/i).length).toBeGreaterThan(0))
  })

  it('never renders anything key-shaped', async () => {
    const user = userEvent.setup()
    mockApi(STATUS_OK)
    const { container } = wrap(<Assistant />)
    await waitFor(() => expect(screen.getByRole('textbox')).toBeInTheDocument())
    await user.type(screen.getByRole('textbox'), 'Explain this forecast')
    await user.click(screen.getByRole('button', { name: /^ask$/i }))
    await waitFor(() =>
      expect(screen.getByText(/broadly stable/i)).toBeInTheDocument())
    expect(container.textContent).not.toMatch(/AIza[0-9A-Za-z_-]{20,}/)
    expect(container.textContent).not.toMatch(/GEMINI_API_KEY\s*=\s*\S/)
  })
})
